WITH MemberCounts AS (
    SELECT MEMBER_ID, COUNT(*) AS CountPerMember
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MaxCount AS (
    SELECT MAX(CountPerMember) AS MaxCount
    FROM MemberCounts
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS A
JOIN MEMBER_PROFILE AS B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM MemberCounts
    WHERE CountPerMember = (SELECT MaxCount FROM MaxCount)
)
ORDER BY REVIEW_DATE, REVIEW_TEXT