SELECT FLAVOR
FROM
(
    SELECT A.FLAVOR, (A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM
        FIRST_HALF AS A
    JOIN
        (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
        ) AS B
    ON A.FLAVOR = B.FLAVOR
) COMBINED_TABLE
ORDER BY TOTAL_ORDER DESC
LIMIT 3