SELECT DISTINCT USER_ID, NICKNAME, CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소, CONCAT_WS("-", SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
WHERE WRITER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) > 2 )
ORDER BY USER_ID DESC